Repository kidsakoder/kidsakoder-no-app, pull requests merged in 2018-05, with the labels that each got.

#74 Feature/makefile
  Makefile
Labels: Priority: Low, Type: Enhancement, Type: Setup

#78 Filter news and events by published
  code/src/main/resources/assets/js/apps/events.js
  code/src/main/resources/site/content-types/event/event.xml
  code/src/main/resources/site/parts/event/event.es6
  code/src/main/resources/site/parts/event/event.html
  code/src/main/resources/site/parts/event/event.xml
  code/src/main/resources/site/parts/events/events.html
  code/src/main/resources/site/parts/news-list/news-list.es6
  code/src/main/resources/site/parts/news-list/news-list.html
  code/src/main/resources/site/parts/news-list/news-list.xml
Labels: Priority: High, Type: Feature

#81 Feature/react tests
  Makefile
  README.md
  code/package.json
  code/src/main/resources/assets/js/apps/events.test.js
  code/webpack.config.js
  scripts/clean.sh
  scripts/templates/docker-compose.dev.yml.src
  scripts/tests.sh
Labels: Priority: High, Type: Feature

#82 Add 5 tests, new babel, leaflet to map, and make eventlist testable
  code/.babelrc
  code/.eslintrc.json
  code/build.gradle
  code/package.json
  code/src/main/resources/assets/js/apps/components/EventList.js
  code/src/main/resources/assets/js/apps/components/Map.js
  code/src/main/resources/assets/js/apps/components/MapPortal.js
  code/src/main/resources/assets/js/apps/events.js
  code/src/main/resources/assets/js/apps/events.test.js
  code/src/main/resources/assets/js/apps/test/helpers/setup.js
  code/src/main/resources/site/pages/default/default.html
  code/src/main/resources/site/parts/map/map.es6
  code/webpack.config.js
  scripts/clean.sh
Labels: Priority: High, Type: Feature

#84 Make articles listed after placed into view
  code/src/main/resources/site/parts/news-list/news-list.es6
Labels: Priority: Medium, Type: Hotfix

#88 Change all display names to norwegian
  code/src/main/resources/site/content-types/event/event.xml
  code/src/main/resources/site/content-types/news-element/news-element.xml
  code/src/main/resources/site/pages/default/default.xml
  code/src/main/resources/site/parts/events/events.xml
  code/src/main/resources/site/parts/main-button/main-button.es6
  code/src/main/resources/site/parts/main-button/main-button.html
  code/src/main/resources/site/parts/main-button/main-button.xml
  code/src/main/resources/site/parts/map/map.xml
  code/src/main/resources/site/parts/news-list/news-list.xml
Labels: Priority: Low, Type: Enhancement

#89 Interactive map for events
  code/src/main/resources/assets/css/components/_events.scss
  code/src/main/resources/assets/css/themes/_theme.scss
  code/src/main/resources/assets/js/apps/components/EventList.js
  code/src/main/resources/assets/js/apps/components/Map.js
  code/src/main/resources/assets/js/apps/components/MapPortal.js
  code/src/main/resources/assets/js/apps/events.js
  code/src/main/resources/assets/js/apps/events.test.js
  code/src/main/resources/site/content-types/event/event.xml
  code/src/main/resources/site/parts/event/event.es6
  code/src/main/resources/site/parts/event/event.html
Labels: Priority: Medium, Type: Feature

#91 Hotfix template error
  code/src/main/resources/site/parts/event/event.es6
Labels: Priority: High, Type: Bug

#95 Add delay to React app error message
  code/src/main/resources/assets/css/components/_events.scss
  code/src/main/resources/site/parts/events/events.html
Labels: Priority: Low, Type: Enhancement

#96 Fix map duplicates
  code/src/main/resources/assets/js/apps/components/MapPortal.js
Labels: Priority: Low, Type: Enhancement

#98 Add header link to home page
  code/src/main/resources/site/pages/default/header.html
Labels: Priority: Low, Type: Enhancement

#100 Fix #92 root URL for event list
  code/src/main/resources/assets/js/apps/components/EventList.js
  code/src/main/resources/assets/js/apps/events.test.js
  code/src/main/resources/site/parts/events/events.html
Labels: Priority: High, Type: Bug

#101 Use a replace function instead of split to solve issue #92
  code/src/main/resources/assets/js/apps/components/EventList.js
Labels: Priority: High, Type: Bug

#102 Fix #92 yet another time. This time it will work
  code/src/main/resources/assets/js/apps/components/EventList.js
  code/src/main/resources/assets/js/apps/events.js
  code/src/main/resources/assets/js/apps/events.test.js
Labels: Priority: High, Type: Bug

#99 Remove three column full width option from xml
  code/src/main/resources/site/layouts/three-column/three-column.xml
Labels: Priority: Low, Type: Hotfix

#103 Add HTTPS to leaflet CSS CDN
  code/src/main/resources/site/parts/map/map.es6
Labels: Priority: High, Type: Bug
