Repository kidsakoder/kidsakoder-no-app, pull requests merged in 2018-04, with the labels that each got.

#56 Feature/default landing page
  code/src/main/resources/assets/css/common/layout.scss
  code/src/main/resources/assets/css/common/theme.scss
  code/src/main/resources/assets/images/SAMSUNG_LOGO_BLACK.svg
  code/src/main/resources/assets/images/enonic.svg
  code/src/main/resources/site/mixins/images/images.xml
  code/src/main/resources/site/pages/default/default.es6
  code/src/main/resources/site/pages/default/default.html
  code/src/main/resources/site/pages/default/footer.html
  code/src/main/resources/site/pages/default/header.html
  code/src/main/resources/site/parts/main-button/main-button.xml
  scripts/logs.sh
Labels: Priority: High

#57 Feature/news element
  code/.eslintrc.json
  code/src/main/resources/assets/js/apps/components/Map.js
  code/src/main/resources/assets/js/apps/events.js
  code/src/main/resources/assets/js/apps/landing-page.js
  code/src/main/resources/assets/js/apps/utils/graphql.js
  code/src/main/resources/site/content-types/news-element/news-element.xml
  code/src/main/resources/site/layouts/one-column/one-column.es6
  code/src/main/resources/site/layouts/three-column/three-column.es6
  code/src/main/resources/site/pages/default/default.es6
  code/src/main/resources/site/parts/article/article.html
  code/src/main/resources/site/parts/article/article.js
  code/src/main/resources/site/parts/article/article.xml
  code/src/main/resources/site/parts/events/events.es6
  code/src/main/resources/site/parts/main-button/main-button.es6
  code/src/main/resources/site/parts/map/map.es6
  code/src/main/resources/site/parts/news-element/news-element.es6
  code/src/main/resources/site/parts/news-element/news-element.html
  code/src/main/resources/site/parts/news-element/news-element.xml
  code/src/main/resources/site/parts/news-item/news-item.html
  code/src/main/resources/site/parts/news-item/news-item.js
  code/src/main/resources/site/parts/news-item/news-item.xml
  code/src/main/resources/site/parts/news-list/news-list.es6
  code/src/main/resources/site/parts/news-list/news-list.html
  code/src/main/resources/site/parts/news-list/news-list.xml
Labels: Priority: Medium, Type: Feature

#58 Color palette
  code/src/main/resources/assets/css/common/theme.scss
Labels: Priority: Medium, Type: Chore

#60 Fix background color
  code/src/main/resources/assets/css/common/theme.scss
Labels: Priority: High, Type: Bug

#61 Render HTML in utext in news article
  code/src/main/resources/site/parts/news-element/news-element.html
Labels: Priority: Medium, Type: Feature

#62 Remove editor specific settings
  .vscode/settings.json
Labels: Priority: Low, Type: Hotfix

#68 Remove ingress and change content name
  code/src/main/resources/site/content-types/event/event.xml
Labels: Priority: Low, Type: Enhancement

#70 Add the ability for news-element part to show the main image
  code/src/main/resources/site/content-types/news-element/news-element.xml
  code/src/main/resources/site/parts/news-element/news-element.es6
  code/src/main/resources/site/parts/news-element/news-element.html
Labels: Priority: Low, Type: Hotfix

#71 Enonic routing
  code/build.gradle
  code/src/main/resources/site/pages/default/default.es6
  code/src/main/resources/site/pages/default/header.html
  code/src/main/resources/site/parts/news-element/news-element.es6
  code/src/main/resources/site/parts/news-element/news-element.xml
  code/src/main/resources/site/parts/news-list/news-list.es6
  code/src/main/resources/site/parts/news-list/news-list.html
  code/src/main/resources/site/site.xml
Labels: Priority: High, Type: Feature

#69 feature/redesign
  code/src/main/resources/assets/css/base/_button.scss
  code/src/main/resources/assets/css/base/_media.scss
  code/src/main/resources/assets/css/base/_normalize.scss
  code/src/main/resources/assets/css/common/layout.scss
  code/src/main/resources/assets/css/components/_events.scss
  code/src/main/resources/assets/css/components/_nav-button.scss
  code/src/main/resources/assets/css/defaultPage.scss
  code/src/main/resources/assets/css/defaultPageButton.scss
  code/src/main/resources/assets/css/layouts/_footer.scss
  code/src/main/resources/assets/css/layouts/_header.scss
  code/src/main/resources/assets/css/layouts/_inner-wrapper.scss
  code/src/main/resources/assets/css/layouts/_main.scss
  code/src/main/resources/assets/css/main.scss
  code/src/main/resources/assets/css/pages/_landing-page.scss
  code/src/main/resources/assets/css/themes/_theme.scss
  code/src/main/resources/assets/images/lkk-logo/lkk-logo-url-negativ-sorthvit.svg
  code/src/main/resources/assets/images/lkk-logo/lkk-logo-url-positiv-farge.svg
  code/src/main/resources/assets/images/lkk-logo/lkk-logo-url-positiv-sorthvit.svg
  code/src/main/resources/assets/images/sponsor-logo/SAMSUNG_LOGO_BLACK.svg
  code/src/main/resources/assets/images/sponsor-logo/enonic.svg
  code/src/main/resources/site/pages/default/default.es6
  code/src/main/resources/site/pages/default/default.html
  code/src/main/resources/site/pages/default/footer.html
  code/src/main/resources/site/pages/default/header.html
Labels: Priority: High, Status: Work In Progress, Type: Feature

#72 Remove fonts
  code/src/main/resources/assets/css/layouts/_footer.scss
  code/src/main/resources/assets/fonts/bootstrap/glyphicons-halflings-regular.eot
  code/src/main/resources/assets/fonts/bootstrap/glyphicons-halflings-regular.svg
  code/src/main/resources/assets/fonts/bootstrap/glyphicons-halflings-regular.ttf
  code/src/main/resources/assets/fonts/bootstrap/glyphicons-halflings-regular.woff
  code/src/main/resources/assets/fonts/bootstrap/glyphicons-halflings-regular.woff2
  code/src/main/resources/site/pages/default/footer.html
Labels: Type: Hotfix

#73 Feature/design articles
  code/src/main/resources/assets/css/base/_imports.scss
  code/src/main/resources/assets/css/main.scss
  code/src/main/resources/assets/css/pages/_landing-page.scss
  code/src/main/resources/assets/css/pages/_news-article.scss
  code/src/main/resources/assets/css/themes/_theme.scss
  code/src/main/resources/site/parts/news-element/news-element.es6
  code/src/main/resources/site/parts/news-element/news-element.html
Labels: Priority: Medium, Type: Feature
